const textKeys = {
    "taxiDriver":"TAXI DRIVER",
    "password": "Password",
    "ok": "OK",
    "taxi": "TAXI",
    "driver":'DRIVER',
    "create": "Create",
    "submit": "Submit",
    "history": "History",
    'accept': 'Accept',
    'reject': "Reject",
    'pickup': "PickUp",
    'location': "Location",
    'continue': "Continue",
    'straight': "Straight",
    'left': "Left",
    'right': "Right",
    'turn': "Turn",
     "driverReminder": "Let People Know if you are accepting rides",
     "online": "Online",
     "offline": "Offline",
     "rideReview": "How was your Trip",
     "done": "Done",
     'comment': "Write A Comment",  
     'driverOpportunities': "Higher ride activity today at",
     'from': "From",
     'to': "To",
     'day':"Day",
     'week': "Week",
     'Month': "Month",
     "uploadPhoto": "Upload Photo", 
    "fullName": "Full Name",
    "phoneNumber": "Phone Number",
    "email": "Email",
    "login":{ 
        "login": "Log In",
        "username": "Username",
        "forgotPassword": "FORGOT PASSWORD?",
        "createAccount": "CREATE ACCOUNT"
    },
    "signup":{
        "createUsername": "Create Username",
        "confirmPassword": "Confirm Password"
    },
    "confirmAccount": {
        "verifYEmail": "Verify Your Email",
        "textcodeVerification": "Enter The 6 digit code sent to",
        "codeVerification": "Verification Code",
        "resendCode": "RESEND CODE",
        "allSetUp": " You're All Set Up!"
    },
    "menu":{
        "earnings": "Earnings",
        "earning": "Earning",
        "cashOut": "Cash Out",
        "trip": "Trip",
        "stats": "Stats",
        "payment": "Payment",
        "info": "Info",
        "faq": "FAD & Help",
        "settings": "Settings",
        "contact": "Contact US",
        "logout":" Log Out",
    },
    "weekDay":{
         "m": "M",
         "t": "Tu",
         "w": "W",
         "th": "Th",
         "f": "F",
         "s": "Sa",
         "su": "Su"
    }
    
 };
 export default textKeys;