const textKeys = {
    "taxiDriver":"TAXI DRIVER",
    "password": "Password",
    "ok": "OK",
    "am":"AM",
    "pm": "PM",
    "end": "End",
    "this": "This",
    "taxi": "TAXI",
    "driver":'DRIVER',
    "create": "Create",
    "submit": "Submit",
    "history": "History",
    'accept': 'Accept',
    'reject': "Reject",
    'pickup': "Pickup",
    'location': "Location",
    'continue': "Continue",
    'straight': "Straight",
    'destination': "Where do you need to go?",
    'left': "Left",
    'right': "Right",
    'turn': "Turn",
    "arrival": "arrival",
    "min": "min",
    "mi": "mi",
     "driverReminder": "Let People Know if you are accepting rides",
     "online": "Online",
     "offline": "Offline",
     "rideReview": "How was your Trip",
     "done": "DONE",
     'comment': "Write A Comment", 
     'opportunityMessage': "Higher ride activity today at",
     'driverOpportunity': 'Driver Opportunities',
     'from': "From",
     'to': "To",
     'the': "The",
     'day':"Day",
     'week': "Week",
     'month': "Month",
     "uploadPhoto": "Upload Photo", 
    "fullName": "Full Name",
    "phoneNumber": "Phone Number",
    "email": "Email",
    "login":{ 
        "login": "Log In",
        "username": "Username",
        "forgotPassword": "FORGOT PASSWORD?",
        "createAccount": "CREATE ACCOUNT"
    },
    "signup":{
        "createUsername": "Create Username",
        "confirmPassword": "Confirm Password"
    },
    "confirmAccount": {
        "verifYEmail": "Verify Your Email",
        "textcodeVerification": "Enter The 6 digit code sent to",
        "codeVerification": "Verification Code",
        "resendCode": "RESEND CODE",
        "allSetUp": " You're All Set Up!"
    },
    "menu":{
        "earnings": "Earnings",
        "earning": "Earning",
        "cashOut": "Cash Out",
        "trip": "Trip",
        "stats": "Stats",
        "payment": "Payment",
        "info": "Info",
        "faq": "FAQ & Help",
        "settings": "Settings",
        "contact": "Contact US",
        "logout":" Log Out",
        "schedule":"Scheduled Pickups"
    },
    "acceptTrip":{
        "acceptTrip": "Accept Trip?",
        "trip": "Trip Earnings: "
    },
    "weekDay":{
         "m": "M",
         "t": "Tu",
         "w": "W",
         "th": "Th",
         "f": "F",
         "s": "Sa",
         "su": "Su"
    }
    
 };
 export default textKeys;